In [1]:
import numpy as np

y_predicted = np.array([1,1,0,0,1])
y_true = np.array([0.30, 0.7, 1, 0, 0.5])

In [5]:
def mae(y_true, y_predicted):
    total_error = 0
    for yt, yp in zip(y_true, y_predicted):
        total_error += abs(yt - yp)
        
    print("Total error:", total_error)
    mae = total_error / len(y_true)
    print("MAE:", mae)
    return mae

In [6]:
mae(y_true, y_predicted)

Total error: 2.5
MAE: 0.5


0.5

In [7]:
np.abs(y_predicted - y_true)

array([0.7, 0.3, 1. , 0. , 0.5])

In [8]:
np.mean(np.abs(y_predicted - y_true))

0.5

In [11]:
#binary crossentropy
np.log([0.000000000000000001])

array([-41.44653167])

In [13]:
epsilon = 1e-15

In [14]:
y_predicted_new = [max(i, epsilon) for i in y_predicted]
y_predicted_new

[1, 1, 1e-15, 1e-15, 1]

In [15]:
y_predicted_new = [min(i, 1-epsilon) for i in y_predicted]
np.log(y_predicted_new)

C:\Users\Archita Shrivastava\AppData\Local\Temp\ipykernel_9092\1022494799.py:2: RuntimeWarning: divide by zero encountered in log
  np.log(y_predicted_new)


array([-9.99200722e-16, -9.99200722e-16,            -inf,            -inf,
       -9.99200722e-16])

In [21]:
y_predicted_new = np.array(y_predicted_new)
np.log(y_predicted_new)

C:\Users\Archita Shrivastava\AppData\Local\Temp\ipykernel_9092\2029199556.py:2: RuntimeWarning: divide by zero encountered in log
  np.log(y_predicted_new)


array([-9.99200722e-16, -9.99200722e-16,            -inf,            -inf,
       -9.99200722e-16])

In [23]:
-np.mean(y_true * np.log(y_predicted_new) + (1 - y_true) * np.log(1 - y_predicted_new))

C:\Users\Archita Shrivastava\AppData\Local\Temp\ipykernel_9092\2763955057.py:1: RuntimeWarning: divide by zero encountered in log
  -np.mean(y_true * np.log(y_predicted_new) + (1 - y_true) * np.log(1 - y_predicted_new))
C:\Users\Archita Shrivastava\AppData\Local\Temp\ipykernel_9092\2763955057.py:1: RuntimeWarning: invalid value encountered in multiply
  -np.mean(y_true * np.log(y_predicted_new) + (1 - y_true) * np.log(1 - y_predicted_new))


nan

In [28]:
def log_loss(y_true, y_predicted):
    y_predicted_new = [max(i, epsilon) for i in y_predicted]
    y_predicted_new = [max(i, epsilon) for i in y_predicted_new]
    y_predicted_new = np.array(y_predicted_new)+(1-y_predicted_new)
    return -np.mean(y_true*np.og(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

In [31]:
import numpy as np

def log_loss(y_true, y_predicted):
    epsilon = 1e-15
    y_predicted = np.clip(y_predicted, epsilon, 1 - epsilon)
    return -np.mean(y_true * np.log(y_predicted) + (1 - y_true) * np.log(1 - y_predicted))

In [32]:
# Sample data
y_true = np.array([1, 0, 1, 1, 0])
y_predicted = np.array([0.9, 0.1, 0.8, 0.4, 0.2])

# Call the function
loss_value = log_loss(y_true, y_predicted)
print(f"Log loss: {loss_value}")

Log loss: 0.3146597731636454
