In [1]:
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding

In [2]:
reviews = ['nice food',
          'amazing resturant',
          'too good',
          'just loved it !',
          'will go again',
          'horrible food',
          'never go there',
          'poor service',
          'poor quality',
          'needs improvement']

sentiment = np.array([1,1,1,1,1,0,0,0,0,0])

In [4]:
one_hot("amazing resturant", 30)

[27, 25]

In [5]:
vocab_size = 30
encoded_reviews = [one_hot(d, vocab_size) for d in reviews]
encoded_reviews

[[17, 16],
 [27, 25],
 [20, 10],
 [19, 22, 23],
 [16, 7, 20],
 [20, 16],
 [29, 7, 8],
 [2, 18],
 [2, 9],
 [24, 25]]

In [8]:
max_length = 4
padded_reviews = pad_sequences(encoded_reviews, maxlen = max_length, padding = 'post')
print(padded_reviews)

[[17 16  0  0]
 [27 25  0  0]
 [20 10  0  0]
 [19 22 23  0]
 [16  7 20  0]
 [20 16  0  0]
 [29  7  8  0]
 [ 2 18  0  0]
 [ 2  9  0  0]
 [24 25  0  0]]


In [12]:
embedded_vector_size = 5
model = Sequential()
model.add(Embedding(vocab_size, embedded_vector_size, input_length = max_length, name = "embedding"))
model.add(Flatten())
model.add(Dense(1, activation = 'sigmoid'))

In [13]:
X = padded_reviews
y = sentiment

In [14]:
model.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 4, 5)              150       
                                                                 
 flatten (Flatten)           (None, 20)                0         
                                                                 
 dense (Dense)               (None, 1)                 21        
                                                                 
Total params: 171
Trainable params: 171
Non-trainable params: 0
_________________________________________________________________


In [15]:
model.fit(X, y, epochs = 50, verbose = 0 )

In [16]:
loss, accuracy = model.evaluate(X,y)
accuracy

1/1 [==============================] - 1s 739ms/step - loss: 0.6320 - accuracy: 0.9000


0.8999999761581421

In [19]:
weights = model.get_layer('embedding').get_weights()[0]
weights

array([[ 0.03297537,  0.00305839, -0.03647677,  0.02238678, -0.03848007],
       [ 0.02807729,  0.02239417, -0.03983577,  0.01076355,  0.03532955],
       [ 0.01538965,  0.08496923,  0.05004115, -0.02055243, -0.09324964],
       [-0.00356521, -0.02493905, -0.03733005,  0.03233938,  0.04163979],
       [ 0.01720207,  0.02875232,  0.00684404, -0.01322304,  0.00218567],
       [ 0.028924  , -0.02148401, -0.04367815,  0.02190396, -0.01198149],
       [-0.02611622, -0.01558704,  0.04497267, -0.04337754, -0.03938945],
       [-0.02646422, -0.01606686, -0.0352604 , -0.01638513,  0.05234046],
       [ 0.10669474,  0.07643963, -0.0912013 ,  0.04973642, -0.10011095],
       [ 0.08540724, -0.06986559, -0.02234429,  0.02525342,  0.03334451],
       [-0.03041912,  0.08558788,  0.03193779, -0.02088522, -0.09883703],
       [-0.01955441,  0.03830495, -0.02758476,  0.01690536, -0.00990362],
       [ 0.02934827, -0.02843813, -0.03587327, -0.02253808, -0.00361877],
       [ 0.03209723, -0.0051734 , -0.0

In [20]:
weights[11]

array([-0.01955441,  0.03830495, -0.02758476,  0.01690536, -0.00990362],
      dtype=float32)

In [21]:
weights[12]

array([ 0.02934827, -0.02843813, -0.03587327, -0.02253808, -0.00361877],
      dtype=float32)

In [22]:
weights[3]

array([-0.00356521, -0.02493905, -0.03733005,  0.03233938,  0.04163979],
      dtype=float32)