In [1]:
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding

In [2]:
reviews = ['nice food',
          'amazing resturant',
          'too good',
          'just loved it !',
          'will go again',
          'horrible food',
          'never go there',
          'poor service',
          'poor quality',
          'needs improvement']

sentiment = np.array([1,1,1,1,1,0,0,0,0,0])

In [3]:
one_hot("amazing resturant", 30)

[18, 13]

In [4]:
vocab_size = 30
encoded_reviews = [one_hot(d, vocab_size) for d in reviews]
encoded_reviews

[[24, 13],
 [18, 13],
 [18, 24],
 [10, 2, 24],
 [9, 16, 16],
 [13, 13],
 [1, 16, 23],
 [19, 26],
 [19, 18],
 [15, 18]]

In [5]:
max_length = 3
padded_reviews = pad_sequences(encoded_reviews, maxlen = max_length, padding = 'post')
print(padded_reviews)

[[24 13  0]
 [18 13  0]
 [18 24  0]
 [10  2 24]
 [ 9 16 16]
 [13 13  0]
 [ 1 16 23]
 [19 26  0]
 [19 18  0]
 [15 18  0]]


In [13]:
embedded_vector_size = 5

model = Sequential()
model.add(Embedding(vocab_size, embedded_vector_size, name="embeddings"))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

X = padded_reviews
y = sentiment

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.summary()  # Now this will actually print the summary


Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embeddings (Embedding)               │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ flatten_2 (Flatten)                  │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_2 (Dense)                      │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [14]:
model.fit(X, y, epochs =50, verbose =0)

In [15]:
#evaluate the model
loss, accuracy = model.evaluate(X,y)
accuracy

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 644ms/step - accuracy: 1.0000 - loss: 0.6034


1.0

In [18]:
weights = model.get_layer('embeddings').get_weights()[0]
len(weights)

30

In [19]:
weights[11]

array([-0.01225439, -0.03026971,  0.02566751, -0.03894588,  0.01716584],
      dtype=float32)

In [20]:
weights[3]

array([-0.01605982,  0.03125537,  0.03651744,  0.04560176, -0.01015411],
      dtype=float32)